---
title: "OLS Consistency"
author: "Halina Do-Linh"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# EDS241: Simulations of consistency of OLS and omitted variable bias  
# created: 01/05/2022
# updated: 01/06/2022

# Packages
```{r}
#install.packages("ggplot2")
#install.packages("huxtable")
#install.packages("ggthemes")
library("ggplot2")
library("huxtable")
library("ggthemes")
```

# 1. Demonstrating consistency of OLS under LSA 1-3

```{r}
set.seed(124577) # original number 124578

bigN <- 10000

# Generate X1 and u
X1 <- runif(bigN, min = 0, max = 10) # regular uniform random variable that's what runif is
u <- rnorm(bigN, mean = 0, sd = 4) # look into what rnorm is
```

```{r}
# Bivariate population regression function
Y <- 5 + 1.5*X1 + u
population_data <- data.frame(X1, Y)
```


```{r}
# OLS estimation, full sample
model1 <- lm(formula = Y ~ X1, data = population_data)
huxreg(model1, error_pos="right")
```


```{r}
# OLS estimation, with sample size increasing from n=1 to 10,000
betahat_output <- matrix(ncol = 2, nrow = bigN)

for (n in 1:bigN) {
  sample <- population_data[1:n,]
  betahat_output[n,] <- lm(Y ~ X1, data = sample)$coefficients
} 

n <- seq(1,bigN)
beta1hat <- betahat_output[,c(2)]
forgraph <- data.frame(n , betahat_output[,c(2)])
```


```{r}
# Graphing the results
ggplot(forgraph , aes(x=n, y=beta1hat)) + geom_line(size=0.5, color="blue") +
  geom_hline(yintercept=1.5, size=2, color="red") +
  labs(x="n", y = "Beta1hat") + 
  ggthemes::theme_pander(base_size = 14) 
```


```{r}
# 2. Demonstrating omitted variables bias

X2 = X1 +rnorm(bigN , mean=0 , sd=2.2)
```

```{r}
# Multiple population regression function
Y <- 5 + 1.5*X1 + 10*X2 + u
population_data <- data.frame(X1, Y)
```

```{r}
# OLS estimation, full sample, but ignoring X2
model1 <- lm(formula = Y ~ X1, data = population_data)
huxreg(model1, error_pos="right")
```

```{r}
# Compute correlation between X1 and X2, and standard deviations
# Compute "probability limit" of Beta1_hat
cor(X1,X2)
sd(X1)
sd(X2)
1.5 + 10*cor(X1,X2)*sd(X2)/sd(X1)
```

```{r}
# OLS estimation, with sample size increasing from n=1 to 10,000
betahat_output <- matrix(ncol = 2, nrow = bigN)

for (n in 1:bigN) {
  sample <- population_data[1:n,]
  betahat_output[n,] <- lm(Y ~ X1, data = sample)$coefficients
} 

n <- seq(1,bigN) 
beta1hat <- betahat_output[,c(2)]
forgraph <- data.frame(n , betahat_output[,c(2)])

ggplot(forgraph , aes(x=n, y=beta1hat)) + geom_line(size=0.5, color="blue") +
  geom_hline(yintercept=1.5, size=2, color="red") +
  labs(x="n", y = "Beta1hat") + 
  ggthemes::theme_pander(base_size = 14) 
```


